# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: Build Cool Web Stuff
title: G
description: SLiK Blog
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

front-page-posts: 2

permalink: /:categories/:year/:month/:day/:title:output_ext

linkedin_username: gary-saunders-sd
github_username: slik1

# Build settings
# Jekyll 3 now only supports Kramdown for Markdown
markdown: kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Layout settings
home-link-in-menu: yes

# Gems
plugins:
  - jekyll-paginate

paginate: 3
